# -*- coding: utf-8 -*-
"""dados_simulator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pqbIRx7TvGGHwXcYks2eBtasa4jtyKfS

# VOCÊ TEM DADO EM CASA?
## Se a resposta é "não" seus problemas acabaram:
### chegou o revolucionário Dados Digital Simulator Tabajara!
"""

from random import choice

d4 = list(range(1, 5))
d6 = list(range(1, 7))
d8 = list(range(1, 9))  
d10 = list(range(1, 11))
d12 = list(range(1, 13))
d20 = list(range(1, 21))

d = int(input("escolha tipo de dado? "))


quantos = int(input("qua8ntos dados? "))


if d == 6:
    for i in range(quantos):
        print(choice(d6))

if d == 8:
    for i in range(quantos):
        print(choice(d8))

# https://www.hashtagtreinamentos.com/match-case-no-python?gad_source=1&gclid=Cj0KCQjwrKu2BhDkARIsAD7GBovgHbu7CZWmwZgBCC4Fh65IGzoKNfIJoRHT042Q6GV7kQ1aBOPPKKgaAjsFEALw_wcB